version: '3.9'

services:
  php-cli:
    restart: unless-stopped
    container_name: BSB_php
    profiles: ["main", "dev"]
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ${BACKUPS_FOLDER}:/app/backups
    depends_on:
      - composer
    networks:
      - app_network

  composer:
    restart: unless-stopped
    container_name: BSB_composer
    profiles: ["main", "dev"]
    image: composer:2.6.5
    volumes:
      - ./app:/app
    working_dir: /app
    command: install
    networks:
      - app_network

networks:
  app_network:
    driver: bridge